version : "3"
services:
  app:
    container_name: agl_m1sir
    image: agl_m1sir
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    container_name: agl_m1sir-db
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: projetsir
    volumes:
      - ./db-data:/var/lib/postgresql/data

